sudo: required
language:
  - cpp
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - curl
            - libx11-dev
            - libglu1-mesa-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - zlib1g-dev
            - libasound2-dev
            - libgtk2.0-dev
            - libjack-jackd2-dev
            - python3-pip
            - python3-setuptools
    - os: osx
    - os: windows

before_script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]
      then
        PowerShell -Command choco install -y python3 msys2
        PowerShell -Command pacman -Syu
        PowerShell -Command pacman -Su git wget make tar unzip zip mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake autoconf automake mingw-w64-x86_64-libtool mingw-w64-x86_64-jq
        PowerShell -Command pip3 install --upgrade pip
        PowerShell -Command pip3 install user conan
    else
      pip install --user --upgrade pip
      pip3 install --user --upgrade pip
      pip3 install --user conan
    fi

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - python --version
  - conan --version
  - make dep
  - make
