dist: xenial
sudo: required
language:
  - cpp
compiler:
  - gcc
  - g++

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          packages:
            - g++
            - gcc
            - build-essential
            - git
            - curl
            - cmake
            - libx11-dev
            - libglu1-mesa-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - zlib1g-dev
            - libasound2-dev
            - libgtk2.0-dev
            - libjack-jackd2-dev
            - jq

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - lsb_release -a
  - cmake --version
  - gcc --version
  - g++ --version
  - ls -lisa
  - pwd
  - git submodule update --init --recursive
  - make dep
  - make
  - make install
