sudo: required
language:
  - cpp
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - curl
            - libx11-dev
            - libglu1-mesa-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - zlib1g-dev
            - libasound2-dev
            - libgtk2.0-dev
            - libjack-jackd2-dev
            - python3-pip
            - python3-setuptools
    - os: osx
    - os: windows

before_script:
  - |
    pip3 install --user --upgrade pip
    pip3 install --user conan

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - python --version
  - conan --version
  - make dep
  - make
