# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    sudo apt update -y
    sudo apt install -y \
    curl libcurl4-openssl-dev libx11-dev libglu1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev \
    libxi-dev zlib1g-dev libasound2-dev libgtk2.0-dev libjack-jackd2-dev jq
    pip3 install --user --upgrade pip
    pip3 install --user conan
  displayName: "install dependencies"
- script: |
    git submodule update --init --recursive
    make dep
    make
  displayName: "build VCVRack Linux"
